const tiles = [
    {
        name: "Go",
        position: 0,
        type: "go",
    },
    {
        name: "Mediterranean",
        cost: 60,
        upgrade: 50,
        position: 1,
        group: "purple",
        rent: [
            2, 10, 30, 90, 160, 250,
        ],
        type: "property",
    },
    {
        name: "Community Chest",
        position: 2,
        type: "chest",
    },
    {
        name: "Baltic",
        cost: 60,
        upgrade: 50,
        position: 3,
        group: "purple",
        rent: [
            4, 20, 60, 180, 320, 450,
        ],
        type: "property",
    },
    {
        name: "Tax",
        position: 4,
        type: "income-tax",
    },
    {
        name: "Reading Railroad",
        cost: 200,
        base_rent: 25,
        position: 5,
        type: "rr",
    },
    {
        name: "Oriental",
        cost: 100,
        upgrade: 50,
        position: 6,
        group: "light-blue",
        rent: [
            6, 30, 90, 270, 400, 550,
        ],
        type: "property",
    },
    {
        name: "Chance",
        position: 7,
        type: "chance",
    },
    {
        name: "Vermont",
        cost: 100,
        upgrade: 50,
        position: 8,
        group: "light-blue",
        rent: [
            6, 30, 90, 270, 400, 550,
        ],
        type: "property",
    },
    {
        name: "Connecticut",
        cost: 120,
        upgrade: 50,
        position: 9,
        group: "light-blue",
        rent: [
            8, 40, 100, 300, 450, 600,
        ],
        type: "property",
    },
    {
        name: "Jail",
        position: 10,
        type: "jail",
    },
    {
        name: "Charles",
        cost: 140,
        upgrade: 100,
        position: 11,
        group: "pink",
        rent: [
            10, 50, 150, 450, 625, 750,
        ],
        type: "property",
    },
    {
        name: "Electric",
        cost: 150,
        position: 12,
        group: "utility",
        type: "utility",
    },
    {
        name: "States",
        cost: 140,
        upgrade: 100,
        position: 13,
        group: "pink",
        rent: [
            10, 50, 150, 450, 625, 750,
        ],
        type: "property",
    },
    {
        name: "Virginia",
        cost: 160,
        upgrade: 100,
        position: 14,
        group: "pink",
        rent: [
            12, 60, 180, 500, 700, 900,
        ],
        type: "property",
    },
    {
        name: "Penn Railroad",
        cost: 200,
        base_rent: 25,
        position: 15,
        type: "rr",
    },
    {
        name: "James",
        cost: 180,
        upgrade: 100,
        position: 16,
        group: "orange",
        rent: [
            14, 70, 200, 550, 750, 950,
        ],
        type: "property",
    },
    {
        name: "Community Chest",
        position: 17,
        type: "chest",
    },
    {
        name: "Tennessee",
        cost: 180,
        upgrade: 100,
        position: 18,
        group: "orange",
        rent: [
            14, 70, 200, 550, 750, 950,
        ],
        type: "property",
    },
    {
        name: "New York",
        cost: 200,
        upgrade: 100,
        position: 19,
        group: "orange",
        rent: [
            16, 80, 220, 600, 800, 1000,
        ],
        type: "property",
    },
    {
        name: "Free Parking",
        position: 20,
        type: "parking",
    },
    {
        name: "Kentucky",
        cost: 220,
        upgrade: 150,
        position: 21,
        group: "red",
        rent: [
            18, 90, 250, 700, 875, 1050,
        ],
        type: "property",
    },
    {
        name: "Chance",
        position: 22,
        type: "chance",
    },
    {
        name: "Indiana",
        cost: 220,
        upgrade: 150,
        position: 23,
        group: "red",
        rent: [
            18, 90, 250, 700, 875, 1050,
        ],
        type: "property",
    },
    {
        name: "Illinois",
        cost: 240,
        upgrade: 150,
        position: 24,
        group: "red",
        rent: [
            20, 100, 300, 750, 925, 1100,
        ],
        type: "property",
    },
    {
        name: "BO Railroad",
        cost: 200,
        base_rent: 25,
        position: 25,
        type: "rr",
    },
    {
        name: "Atlantic",
        cost: 260,
        upgrade: 150,
        position: 26,
        group: "yellow",
        rent: [
            22, 110, 330, 800, 975, 1150,
        ],
        type: "property",
    },
    {
        name: "Ventnor",
        cost: 260,
        upgrade: 150,
        position: 27,
        group: "yellow",
        rent: [
            22, 110, 330, 800, 975, 1150,
        ],
        type: "property",
    },
    {
        name: "Water",
        cost: 150,
        position: 28,
        group: "utility",
        type: "utility",
    },
    {
        name: "Marvin",
        cost: 280,
        upgrade: 150,
        position: 29,
        group: "yellow",
        rent: [
            24, 120, 360, 850, 1025, 1200,
        ],
        type: "property",
    },
    {
        name: "Go to Jail",
        position: 30,
        type: "go-to-jail",
    },
    {
        name: "Pacific",
        cost: 300,
        upgrade: 200,
        position: 31,
        group: "green",
        rent: [
            26, 130, 390, 900, 1100, 1275,
        ],
        type: "property",
    },
    {
        name: "North Carolina",
        cost: 300,
        upgrade: 200,
        position: 32,
        group: "green",
        rent: [
            26, 130, 390, 900, 1100, 1275,
        ],
        type: "property",
    },
    {
        name: "Community Chest",
        position: 33,
        type: "chest",
    },
    {
        name: "Pennsylvania",
        cost: 320,
        upgrade: 200,
        position: 34,
        group: "green",
        rent: [
            28, 150, 450, 1000, 1200, 1400,
        ],
        type: "property",
    },
    {
        name: "Short Railroad",
        cost: 200,
        base_rent: 25,
        position: 35,
        type: "rr",
    },
    {
        name: "Chance",
        position: 36,
        type: "chance",
    },
    {
        name: "Park Place",
        cost: 350,
        upgrade: 200,
        position: 37,
        group: "dark-blue",
        rent: [
            35, 175, 500, 1100, 1300, 1500,
        ],
        type: "property",
    },
    {
        name: "Lux Tax",
        position: 38,
        type: "lux-tax",
    },
    {
        name: "Boardwalk",
        cost: 400,
        upgrade: 200,
        position: 39,
        group: "dark-blue",
        rent: [
            50, 200, 600, 1400, 1700, 2000,
        ],
        type: "property",
    },
];